Implement parseQueryAdapter for RecylerView  - https://github.com/ParsePlatform/Parse-SDK-Android/releases/tag/1.10.0  - https://github.com/ParsePlatform/ParseUI-Android
 Added Picasso Library for image loading
- http://square.github.io/picasso/

Parse required import of modules which resulted in errors when building application.
"Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2"

Issue was related to jar files within libs
—  Jars Removed
       - Parse-1.10.2.jar
       - ParseFacebookUtilsV4-1.10.2.jar
       - ParseTwitterUtils-1.10.2.jar

Removed GSON and associated classes.